# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM golang:1.24-alpine AS builder

WORKDIR /app

# Install git if needed
RUN apk add --no-cache git

# Copy go mod and sum files
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code
COPY . .

# Build the binary
RUN CGO_ENABLED=0 go build -o mcp main.go

FROM alpine:latest

WORKDIR /app

# Copy the binary from the builder
COPY --from=builder /app/mcp ./mcp

ENTRYPOINT ["./mcp"]
